# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Artamis
email: artamis.eth@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Artamis personal website and blog, where I write about topics I am passionate about like engineering, art,
  hacking, game development, website development, finance, books and more. I created this space to share
  my thoughts, ideas, and experiences with the world, looking to inspire people to follow their curiosity to wherever
  it may take them.
baseurl: "" # the subpath of your site, e.g. /blog
domain: artamis.me
url: "https://artamis.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: artam1s
github_username: artam1s
permalink: "/:categories/:title"
breadcrumbs: false
locale: "en"
lunr:
  search_within_pages: true
search: true
paginate: 5
paginate_path: /blog/page:num/
author:
  name: "Artamis"
  avatar: "/assets/images/IMG_0436.jpg"
  bio: "Modern Renaissance Man, a student of the world"
  location: Everywhere
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:hi@artamis.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://www.twitter.com/artam1s"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://www.github.com/artam1s"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/artam1s"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:hi@artamis.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://www.twitter.com/artam1s"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://www.github.com/artam1s"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/artam1s"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#minimal_mistakes_skin: "dirt"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
# Include in processing
include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
